### ISSUE TITLE
鼠标滚轮往下滚会自动下滚?

### ISSUE THREAD

**Issue by noahlann** [kl2426/vue-element-bigdata-table#1]
按照App.vue内的示例同样写了个demo，但是鼠标滚轮往下滚时会自动往下滚 停不下来
拖动滚动条也会自动下滚。。。

现使用版本：
vue 2.5.2
elementui 2.4.5
vue-element-bigdata-table 1.2.1

**Comment by kl2426** [comment]
没法重现， 你是鼠标滚轮按下去了吗。。。

**Comment by noahlann** [comment]
没有按下去，只是数据量一多 (测试时1000条数据，4列) 就会这样。
只要稍微滚快一点就停不下来。。。
高度固定为300px

**Comment by kl2426** [comment]
重新修改了行块计算规则。改成了将每块table高度记录成分组来计算总高度与占位。
